# Generated by Django 5.0.3 on 2024-03-22 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_uri', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CountryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['country', 'abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='HousingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2200)])),
                ('variation', models.DecimalField(decimal_places=5, max_digits=20)),
                ('square_meter_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'ordering': ['country', '-year', '-month'],
            },
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(models.F('name'), name='un_name_country'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(models.F('base_uri'), name='un_base_uri_country'),
        ),
        migrations.AddField(
            model_name='countrystate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='housingdata',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='housingdata',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.countrystate'),
        ),
        migrations.AddConstraint(
            model_name='countrystate',
            constraint=models.UniqueConstraint(models.F('country_id'), models.F('abbreviation'), name='un_country_abbreviation_country_state'),
        ),
        migrations.AddConstraint(
            model_name='countrystate',
            constraint=models.UniqueConstraint(models.F('country_id'), models.F('name'), name='un_country_name_country_state'),
        ),
        migrations.AddConstraint(
            model_name='housingdata',
            constraint=models.UniqueConstraint(models.F('country_id'), models.F('year'), models.F('month'), models.F('state_id'), name='un_country_year_month_state_housing_data'),
        ),
    ]
